[package]
name = "today"
version = "0.1.0"
authors = ["Ishmaeel <Ishmaeel@users.noreply.github.com>"]
edition = "2018"
build = "src/build.rs"

[dependencies]
chrono = "0.4.6"

[build-dependencies]
winres = "0.1.9"
